### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by brunodles** [Dlimaun/apiblueprint-fileref#1]
### TODO
- [ ] Create as a npm package
- [ ] Register as npm developer
- [ ] Publish to npm repository
### Read this
- [Getting Started with NPM](https://gist.github.com/coolaj86/1318304)
- [Creating Node Modules](https://docs.npmjs.com/getting-started/creating-node-modules)
- [Publishing npm Packages](https://docs.npmjs.com/getting-started/publishing-npm-packages)
